# --- CONFIGURACIÓN PRINCIPAL ---
title: "ENFANT TERRIBLE"
description: "The definitive source for ultra-realistic next-gen graphics. Expert analysis on Unreal Engine 5, Unity 6, and 2026's most insane tech demos, gameplay previews, and trailers."
url: "https://www.enfant-terrible.media"
baseurl: ""

# --- TEMA ---
remote_theme: jekyll/minima
minima:
  skin: dark

twitter_username: EnfantTerrible7
# Esto suele activar el icono de RSS automáticamente en Minima
show_excerpts: true 

plugins:
  - jekyll-remote-theme
  - jekyll-feed
