name: Generate Posts from YouTube
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch YouTube Videos and Create Files
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PL7nodL-Tlw8XoChvA8Db7rRCSjd39Mv_M"
          custom_tags: "videoId/yt:videoId/"
          readme_path: "./_posts/"
          output_post_format: "markdown"
          template: |
            ---
            layout: post
            title: "$title"
            date: $date
            image: "$thumbnail"
            ---

            ![Portada de $title]($thumbnail)

            <div class="video-container" style="margin-top: 20px; margin-bottom: 20px;">
              <iframe width="100%" height="400" src="https://www.youtube.com/embed/$videoId" frameborder="0" allowfullscreen></iframe>
            </div>

            ### 📝 Descripción del vídeo
            $description

            ---
            [📺 Watch on YouTube]($url)
